# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b32706b37da6fdf6b097b9e61d20846fd7a832282fd86287489338c2fbdf81fda5aa06922de64c6a849a78386d317a44061efb46a86792d438e7ac41b4c37356

test:
  secret_key_base: 54043dbc17105816623e5073dd68a7f7406578ce68f507a888d6efc7e4262233c443e63a72afcac48eaf016f9110ad23b92f918e4f9816be7315c24fdfe5e822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
